title: Ben Griffin
author: Ben Griffin
theme: minima
email: bendgriffin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio and testing site for me, Ben Griffin. Also testing functionality for a front-end project at work.

# social links
twitter_username: benjgrif # DO NOT include the @ character, or else the build will fail!
github_username:  ben-griffin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
